image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

tasks:
  - init: |
      export EDITOR="command gp open -w" VISUAL="command gp open -w"
    command: exec zsh
